CREATE AGGREGATE FUNCTION fit_linear RETURNS STRING SONAME 'udf_gsl.so';

CREATE AGGREGATE FUNCTION stats_mean RETURNS REAL SONAME 'udf_gsl.so';
CREATE AGGREGATE FUNCTION stats_variance RETURNS REAL SONAME 'udf_gsl.so';
CREATE AGGREGATE FUNCTION stats_sd RETURNS REAL SONAME 'udf_gsl.so';
CREATE AGGREGATE FUNCTION stats_tss RETURNS REAL SONAME 'udf_gsl.so';
