DROP FUNCTION IF EXISTS fit_linear;
DROP FUNCTION IF EXISTS fit_square;

DROP FUNCTION IF EXISTS stats_mean;
DROP FUNCTION IF EXISTS stats_variance;
DROP FUNCTION IF EXISTS stats_sd;
DROP FUNCTION IF EXISTS stats_tss;
DROP FUNCTION IF EXISTS stats_skew;
DROP FUNCTION IF EXISTS stats_kurtosis;
DROP FUNCTION IF EXISTS stats_covariance;
DROP FUNCTION IF EXISTS stats_lag1_autocorrelation;
DROP FUNCTION IF EXISTS stats_correlation;
